## Relu activation

In [27]:
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = []
for i in inputs:
  if i > 0:
    output.append(i)
  else:
    output.append(0)
print(output)

[0, 2, 0, 3.3, 0, 1.1, 2.2, 0]


In [28]:
import numpy as np
inputs = [0, 2, -1, 3.3, -2.7, 1.1, 2.2, -100]
output = np.maximum(0, inputs)
print(output)

[0.  2.  0.  3.3 0.  1.1 2.2 0. ]


In [41]:
class ReLU:
    def forward(self, inputs):
        self.output = np.maximum(0, inputs)

## SoftMax
<p align="center">
 <img src="Image/img2.png" width="500">
</p>

In [29]:
inputs = np.random.randint(1,100, (4,3))

inputs

array([[74, 88, 65],
       [18, 41, 22],
       [95, 27, 16],
       [18, 11, 18]])

In [30]:
exp_values = np.exp(inputs-np.max(inputs, axis=1, keepdims=True))
exp_values

array([[8.31528719e-07, 1.00000000e+00, 1.02618796e-10],
       [1.02618796e-10, 1.00000000e+00, 5.60279644e-09],
       [1.00000000e+00, 2.93748211e-30, 4.90609473e-35],
       [1.00000000e+00, 9.11881966e-04, 1.00000000e+00]])

In [31]:
probs = exp_values/np.sum(exp_values, axis=1, keepdims=True)
probs

array([[8.31528028e-07, 9.99999168e-01, 1.02618711e-10],
       [1.02618796e-10, 9.99999994e-01, 5.60279641e-09],
       [1.00000000e+00, 2.93748211e-30, 4.90609473e-35],
       [4.99772133e-01, 4.55733195e-04, 4.99772133e-01]])

In [32]:
np.sum(probs, axis=1)

array([1., 1., 1., 1.])

In [ ]:
class Softmax:
    def __init__(self):
        pass
    
    def forward(self, inputs):
        exp_values = np.exp(inputs-np.max(inputs, axis=1, keepdims=True))
        probs = exp_values/np.sum(exp_values, axis=1, keepdims=True)
        self.output = probs

In [24]:
class Layer_Dense:
  # Layer initialization
  def __init__(self, n_inputs, n_neurons):
   self.weights = 0.01 * np.random.randn(n_inputs, n_neurons)
   self.biases = np.zeros((1, n_neurons))
  def forward(self, inputs):
    self.output = np.dot(inputs, self.weights) + self.biases

In [21]:
# from NeuralNetwork import Dense_Layer
import nnfs
from nnfs.datasets import spiral_data

In [48]:
x, y = spiral_data(samples=100, classes=3)
activation1 = RELU()
activation2 = Softmax()

dense1 = Layer_Dense(n_inputs=2, n_neurons=3)  #dense layer1
dense2 = Layer_Dense(n_inputs=3, n_neurons=3)  ##dense layer2

dense1.forward(x)
activation1.forward(dense1.output)  #RElU

dense2.forward(activation1.output)
activation2.forward(dense2.output)  #SOFTMAX

print(activation2.output[:5])

[[0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.33333334 0.33333334 0.33333334]
 [0.3333332  0.3333332  0.3333336 ]]


In [ ]:
print(activation2.output.sum(axis=1))


: 

: 

In [19]:
import numpy as np
import nnfs
from nnfs.datasets import spiral_data
nnfs.init()
# Create dataset
X, Y = spiral_data(samples=100, classes=3)

X.shape
Y.shape

(300,)